### PR TITLE
Reference released version

### PR DESCRIPTION
**Pull request by epugh**
### Description
UBI 1.0.0 has been released, update the README

### Issues Resolved

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by msfroh — APPROVED** [review]
Awesome! 

I just (1 hour ago?) saw a post on LinkedIn saying that the spec was released.

**Review by jzonthemtn — APPROVED** [review]

**Comment by jzonthemtn** [comment]
@epugh Sign your commits! :) :)

**Comment by epugh** [comment]
@jzonthemtn  I may need some help on signing..   I was hoping to "amend" my last commit, but doesn't seem to be doing anything...

**Comment by msfroh** [comment]
> @jzonthemtn I may need some help on signing.. I was hoping to "amend" my last commit, but doesn't seem to be doing anything...

I recently moved from developing on my EC2 instance to developing on my laptop (because latency to the EC2 instance from my hotel in Berlin a couple of weeks ago was terrible), so I had to relearn all the code signing tricks.

What I did after pushing an unsigned commit was:

```
export GPG_TTY=$(tty)         # Required to let the curses-based passkey prompt show up
git commit --amend -S         # -S to sign the commit
git push -f origin            # Update my PR
```

Before running `export GPG_TTY=$(tty)`, the `git commit --amend -S` would fail, saying that it wasn't able to unlock my GPG key.

Then to fix things more permanently, I added that `export GPG_TTY=$(tty)` to my `.zshrc`, and ran `git config --global commit.gpgsign true`, so it always tries to sign my commits.

**Comment by jzonthemtn** [comment]
Closing in favor of #17

**Pull request closed without merging**
