### PR TITLE
Capturing index names during queries

### LINKED ISSUE #34: [FEATURE] Capture the name of the index(es) being searched in the `ubi_queries` index
The UBI plugin captures all queries run on OpenSearch and stores the information about each one in the `ubi_queries` index. While the name of the index(es) being searched are in the `query` field, getting the names of the index(es) from that field requires parsing. Additionally, this information should be eventually removed per #32.

Add a new `indexes` field to the `ubi_query` [schema](https://github.com/opensearch-project/user-behavior-insights/blob/main/src/main/resources/queries-mapping.json) for the index(es) being searched.

This will allow consumers of UBI data to be able to choose which index data is being used.

### PR DESCRIPTION
**Pull request by jzonthemtn**
### Description
Captures the indexes for queries.

### Issues Resolved
#34 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by epugh** [comment]
Chatted with @jzonthemtn  and I think my mental challenge here is that if we are not tracking Lucene queries then why track indexes.   They appear to both go kind of hand in hand.   And yet, this isnt' the crux of UBI, as there are other observability tools for tracking what query was run wehre that might be better suited.

@jzonthemtn had a good question, are there click models that care about which indexes the user was interacting with where we would need this data?   @wrigleydan?   @alexeyrodriguez  could you weigh in?

**Comment by wrigleyDan** [comment]
I think from the perspective of implicit judgements the models don't really care about the technical "index" that was queried. Models care more about contextual information like "Did the user search on a phone or a tablet?", "Was the user logged in?", "Was this a full text query or an autocomplete query?".
While some of this information may be encoded in the index (e.g. you could have a separate autosuggest index, so the last question could be answered by knowing which index was hit by the query) I do not see how judgement models would use this information.
These are my thoughts, so I may be missing the point here.

**Comment by jzonthemtn** [comment]
Thanks for the comments. Until there's a clear need, let's close this pull request. Adding `application` in #41 might end up being enough for UBI.

**Comment by epugh** [comment]
Great discussion all!

**Pull request closed without merging**
